-- Student Society: allow multiple active wallet UPI targets

ALTER TABLE public.wallet_upi_settings
  DROP CONSTRAINT IF EXISTS wallet_upi_settings_id_check;

ALTER TABLE public.wallet_upi_settings
  ALTER COLUMN id DROP DEFAULT;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_attribute
    WHERE attrelid = 'public.wallet_upi_settings'::regclass
      AND attname = 'id'
      AND attidentity IN ('a', 'd')
  ) THEN
    ALTER TABLE public.wallet_upi_settings
      ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;
END $$;

ALTER TABLE public.wallet_upi_settings
  ADD COLUMN IF NOT EXISTS sort_order INTEGER NOT NULL DEFAULT 100;

UPDATE public.wallet_upi_settings
SET sort_order = 10
WHERE id = 1
  AND sort_order = 100;

CREATE UNIQUE INDEX IF NOT EXISTS idx_wallet_upi_settings_upi_id_unique
  ON public.wallet_upi_settings ((lower(upi_id)));

CREATE INDEX IF NOT EXISTS idx_wallet_upi_settings_active_sort
  ON public.wallet_upi_settings(is_active DESC, sort_order ASC, created_at DESC);
